// Bundle the same timeline used by Zotero into the standalone Tampermonkey file.
// Generated content has no @require/network dependency and can be checked in CI.
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const target = path.join(root, 'userscripts/zotero-research-webai.user.js');
const script = fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n');
let built = script;
for (const name of ['timeline', 'updates']) {
  const source = fs.readFileSync(path.join(root, 'addon/content/' + name + '.js'), 'utf8').replace(/\r\n/g, '\n').trimEnd();
  const start = '// BEGIN SHARED ' + name.toUpperCase() + ' (generated by scripts/build_userscript.cjs)';
  const end = '// END SHARED ' + name.toUpperCase();
  const first = built.indexOf(start), last = built.indexOf(end);
  if (first < 0 || last < first) throw new Error('Shared ' + name + ' bundle markers missing');
  built = built.slice(0, first) + start + '\n' + source + '\n' + built.slice(last);
}
if (process.argv.includes('--check')) {
  if (built !== script) { console.error('Shared bundles are stale. Run node scripts/build_userscript.cjs'); process.exitCode = 1; }
} else if (built !== script) fs.writeFileSync(target, built, 'utf8');
