// Bundle the same timeline used by Zotero into the standalone Tampermonkey file.
// Generated content has no @require/network dependency and can be checked in CI.
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const target = path.join(root, 'userscripts/zotero-research-webai.user.js');
const source = fs.readFileSync(path.join(root, 'addon/content/timeline.js'), 'utf8').replace(/\r\n/g, '\n').trimEnd();
const script = fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n');
const start = '// BEGIN SHARED TIMELINE (generated by scripts/build_userscript.cjs)';
const end = '// END SHARED TIMELINE';
const first = script.indexOf(start), last = script.indexOf(end);
if (first < 0 || last < first) throw new Error('Shared timeline bundle markers missing');
const built = script.slice(0, first) + start + '\n' + source + '\n' + script.slice(last);
if (process.argv.includes('--check')) {
  if (built !== script) { console.error('Timeline bundle is stale. Run node scripts/build_userscript.cjs'); process.exitCode = 1; }
} else if (built !== script) fs.writeFileSync(target, built, 'utf8');
